// n = name, c = country, cc = ISO code, tz = IANA zone, la/lo = lat/lon, a = search aliases
export const CITIES = [
  { n: "Singapore", c: "Singapore", cc: "SG", tz: "Asia/Singapore", la: 1.35, lo: 103.82 },
  { n: "Hong Kong", c: "Hong Kong SAR", cc: "HK", tz: "Asia/Hong_Kong", la: 22.32, lo: 114.17 },
  { n: "Shanghai", c: "China", cc: "CN", tz: "Asia/Shanghai", la: 31.23, lo: 121.47 },
  { n: "Beijing", c: "China", cc: "CN", tz: "Asia/Shanghai", la: 39.9, lo: 116.4 },
  { n: "Shenzhen", c: "China", cc: "CN", tz: "Asia/Shanghai", la: 22.54, lo: 114.06 },
  { n: "Guangzhou", c: "China", cc: "CN", tz: "Asia/Shanghai", la: 23.13, lo: 113.26 },
  { n: "Taipei", c: "Taiwan", cc: "TW", tz: "Asia/Taipei", la: 25.03, lo: 121.57 },
  { n: "Tokyo", c: "Japan", cc: "JP", tz: "Asia/Tokyo", la: 35.68, lo: 139.69 },
  { n: "Osaka", c: "Japan", cc: "JP", tz: "Asia/Tokyo", la: 34.69, lo: 135.5 },
  { n: "Seoul", c: "South Korea", cc: "KR", tz: "Asia/Seoul", la: 37.57, lo: 126.98 },
  { n: "Manila", c: "Philippines", cc: "PH", tz: "Asia/Manila", la: 14.6, lo: 120.98 },
  { n: "Jakarta", c: "Indonesia", cc: "ID", tz: "Asia/Jakarta", la: -6.21, lo: 106.85 },
  { n: "Bangkok", c: "Thailand", cc: "TH", tz: "Asia/Bangkok", la: 13.76, lo: 100.5 },
  { n: "Ho Chi Minh City", c: "Vietnam", cc: "VN", tz: "Asia/Ho_Chi_Minh", la: 10.82, lo: 106.63, a: "saigon" },
  { n: "Hanoi", c: "Vietnam", cc: "VN", tz: "Asia/Bangkok", la: 21.03, lo: 105.85 },
  { n: "Kuala Lumpur", c: "Malaysia", cc: "MY", tz: "Asia/Kuala_Lumpur", la: 3.14, lo: 101.69 },
  { n: "Mumbai", c: "India", cc: "IN", tz: "Asia/Kolkata", la: 19.08, lo: 72.88, a: "bombay" },
  { n: "Bengaluru", c: "India", cc: "IN", tz: "Asia/Kolkata", la: 12.97, lo: 77.59, a: "bangalore" },
  { n: "Delhi", c: "India", cc: "IN", tz: "Asia/Kolkata", la: 28.61, lo: 77.21, a: "new delhi" },
  { n: "Hyderabad", c: "India", cc: "IN", tz: "Asia/Kolkata", la: 17.39, lo: 78.49 },
  { n: "Chennai", c: "India", cc: "IN", tz: "Asia/Kolkata", la: 13.08, lo: 80.27 },
  { n: "Colombo", c: "Sri Lanka", cc: "LK", tz: "Asia/Colombo", la: 6.93, lo: 79.86 },
  { n: "Dhaka", c: "Bangladesh", cc: "BD", tz: "Asia/Dhaka", la: 23.81, lo: 90.41 },
  { n: "Karachi", c: "Pakistan", cc: "PK", tz: "Asia/Karachi", la: 24.86, lo: 67.01 },
  { n: "Lahore", c: "Pakistan", cc: "PK", tz: "Asia/Karachi", la: 31.55, lo: 74.34 },
  { n: "Dubai", c: "United Arab Emirates", cc: "AE", tz: "Asia/Dubai", la: 25.2, lo: 55.27, a: "uae" },
  { n: "Abu Dhabi", c: "United Arab Emirates", cc: "AE", tz: "Asia/Dubai", la: 24.45, lo: 54.38 },
  { n: "Riyadh", c: "Saudi Arabia", cc: "SA", tz: "Asia/Riyadh", la: 24.71, lo: 46.68 },
  { n: "Doha", c: "Qatar", cc: "QA", tz: "Asia/Qatar", la: 25.29, lo: 51.53 },
  { n: "Tel Aviv", c: "Israel", cc: "IL", tz: "Asia/Jerusalem", la: 32.09, lo: 34.78 },
  { n: "Istanbul", c: "Turkey", cc: "TR", tz: "Europe/Istanbul", la: 41.01, lo: 28.98 },
  { n: "Tehran", c: "Iran", cc: "IR", tz: "Asia/Tehran", la: 35.69, lo: 51.39 },
  { n: "Moscow", c: "Russia", cc: "RU", tz: "Europe/Moscow", la: 55.76, lo: 37.62 },
  { n: "Almaty", c: "Kazakhstan", cc: "KZ", tz: "Asia/Almaty", la: 43.24, lo: 76.89 },
  { n: "Sydney", c: "Australia", cc: "AU", tz: "Australia/Sydney", la: -33.87, lo: 151.21 },
  { n: "Melbourne", c: "Australia", cc: "AU", tz: "Australia/Melbourne", la: -37.81, lo: 144.96 },
  { n: "Brisbane", c: "Australia", cc: "AU", tz: "Australia/Brisbane", la: -27.47, lo: 153.03 },
  { n: "Perth", c: "Australia", cc: "AU", tz: "Australia/Perth", la: -31.95, lo: 115.86 },
  { n: "Adelaide", c: "Australia", cc: "AU", tz: "Australia/Adelaide", la: -34.93, lo: 138.6 },
  { n: "Canberra", c: "Australia", cc: "AU", tz: "Australia/Sydney", la: -35.28, lo: 149.13 },
  { n: "Auckland", c: "New Zealand", cc: "NZ", tz: "Pacific/Auckland", la: -36.85, lo: 174.76 },
  { n: "Wellington", c: "New Zealand", cc: "NZ", tz: "Pacific/Auckland", la: -41.29, lo: 174.78 },
  { n: "London", c: "United Kingdom", cc: "GB", tz: "Europe/London", la: 51.51, lo: -0.13, a: "uk england" },
  { n: "Manchester", c: "United Kingdom", cc: "GB", tz: "Europe/London", la: 53.48, lo: -2.24 },
  { n: "Edinburgh", c: "United Kingdom", cc: "GB", tz: "Europe/London", la: 55.95, lo: -3.19 },
  { n: "Dublin", c: "Ireland", cc: "IE", tz: "Europe/Dublin", la: 53.35, lo: -6.26 },
  { n: "Lisbon", c: "Portugal", cc: "PT", tz: "Europe/Lisbon", la: 38.72, lo: -9.14 },
  { n: "Madrid", c: "Spain", cc: "ES", tz: "Europe/Madrid", la: 40.42, lo: -3.7 },
  { n: "Barcelona", c: "Spain", cc: "ES", tz: "Europe/Madrid", la: 41.39, lo: 2.17 },
  { n: "Paris", c: "France", cc: "FR", tz: "Europe/Paris", la: 48.86, lo: 2.35 },
  { n: "Amsterdam", c: "Netherlands", cc: "NL", tz: "Europe/Amsterdam", la: 52.37, lo: 4.9 },
  { n: "Brussels", c: "Belgium", cc: "BE", tz: "Europe/Brussels", la: 50.85, lo: 4.35 },
  { n: "Berlin", c: "Germany", cc: "DE", tz: "Europe/Berlin", la: 52.52, lo: 13.4 },
  { n: "Munich", c: "Germany", cc: "DE", tz: "Europe/Berlin", la: 48.14, lo: 11.58 },
  { n: "Frankfurt", c: "Germany", cc: "DE", tz: "Europe/Berlin", la: 50.11, lo: 8.68 },
  { n: "Zurich", c: "Switzerland", cc: "CH", tz: "Europe/Zurich", la: 47.38, lo: 8.54 },
  { n: "Geneva", c: "Switzerland", cc: "CH", tz: "Europe/Zurich", la: 46.2, lo: 6.14 },
  { n: "Milan", c: "Italy", cc: "IT", tz: "Europe/Rome", la: 45.46, lo: 9.19 },
  { n: "Rome", c: "Italy", cc: "IT", tz: "Europe/Rome", la: 41.9, lo: 12.5 },
  { n: "Vienna", c: "Austria", cc: "AT", tz: "Europe/Vienna", la: 48.21, lo: 16.37 },
  { n: "Prague", c: "Czechia", cc: "CZ", tz: "Europe/Prague", la: 50.08, lo: 14.44 },
  { n: "Warsaw", c: "Poland", cc: "PL", tz: "Europe/Warsaw", la: 52.23, lo: 21.01 },
  { n: "Stockholm", c: "Sweden", cc: "SE", tz: "Europe/Stockholm", la: 59.33, lo: 18.07 },
  { n: "Oslo", c: "Norway", cc: "NO", tz: "Europe/Oslo", la: 59.91, lo: 10.75 },
  { n: "Copenhagen", c: "Denmark", cc: "DK", tz: "Europe/Copenhagen", la: 55.68, lo: 12.57 },
  { n: "Helsinki", c: "Finland", cc: "FI", tz: "Europe/Helsinki", la: 60.17, lo: 24.94 },
  { n: "Athens", c: "Greece", cc: "GR", tz: "Europe/Athens", la: 37.98, lo: 23.73 },
  { n: "Bucharest", c: "Romania", cc: "RO", tz: "Europe/Bucharest", la: 44.43, lo: 26.1 },
  { n: "Kyiv", c: "Ukraine", cc: "UA", tz: "Europe/Kyiv", la: 50.45, lo: 30.52, a: "kiev" },
  { n: "Reykjavik", c: "Iceland", cc: "IS", tz: "Atlantic/Reykjavik", la: 64.15, lo: -21.94 },
  { n: "Cairo", c: "Egypt", cc: "EG", tz: "Africa/Cairo", la: 30.04, lo: 31.24 },
  { n: "Lagos", c: "Nigeria", cc: "NG", tz: "Africa/Lagos", la: 6.52, lo: 3.38 },
  { n: "Accra", c: "Ghana", cc: "GH", tz: "Africa/Accra", la: 5.6, lo: -0.19 },
  { n: "Nairobi", c: "Kenya", cc: "KE", tz: "Africa/Nairobi", la: -1.29, lo: 36.82 },
  { n: "Johannesburg", c: "South Africa", cc: "ZA", tz: "Africa/Johannesburg", la: -26.2, lo: 28.05 },
  { n: "Cape Town", c: "South Africa", cc: "ZA", tz: "Africa/Johannesburg", la: -33.92, lo: 18.42 },
  { n: "Casablanca", c: "Morocco", cc: "MA", tz: "Africa/Casablanca", la: 33.57, lo: -7.59 },
  { n: "New York", c: "United States", cc: "US", tz: "America/New_York", la: 40.71, lo: -74.01, a: "nyc usa" },
  { n: "Boston", c: "United States", cc: "US", tz: "America/New_York", la: 42.36, lo: -71.06 },
  { n: "Washington, DC", c: "United States", cc: "US", tz: "America/New_York", la: 38.91, lo: -77.04 },
  { n: "Atlanta", c: "United States", cc: "US", tz: "America/New_York", la: 33.75, lo: -84.39 },
  { n: "Miami", c: "United States", cc: "US", tz: "America/New_York", la: 25.76, lo: -80.19 },
  { n: "Chicago", c: "United States", cc: "US", tz: "America/Chicago", la: 41.88, lo: -87.63 },
  { n: "Austin", c: "United States", cc: "US", tz: "America/Chicago", la: 30.27, lo: -97.74 },
  { n: "Dallas", c: "United States", cc: "US", tz: "America/Chicago", la: 32.78, lo: -96.8 },
  { n: "Houston", c: "United States", cc: "US", tz: "America/Chicago", la: 29.76, lo: -95.37 },
  { n: "Denver", c: "United States", cc: "US", tz: "America/Denver", la: 39.74, lo: -104.99 },
  { n: "Phoenix", c: "United States", cc: "US", tz: "America/Phoenix", la: 33.45, lo: -112.07 },
  { n: "Los Angeles", c: "United States", cc: "US", tz: "America/Los_Angeles", la: 34.05, lo: -118.24, a: "la" },
  { n: "San Francisco", c: "United States", cc: "US", tz: "America/Los_Angeles", la: 37.77, lo: -122.42, a: "sf bay area" },
  { n: "Seattle", c: "United States", cc: "US", tz: "America/Los_Angeles", la: 47.61, lo: -122.33 },
  { n: "Portland", c: "United States", cc: "US", tz: "America/Los_Angeles", la: 45.52, lo: -122.68 },
  { n: "Honolulu", c: "United States", cc: "US", tz: "Pacific/Honolulu", la: 21.31, lo: -157.86, a: "hawaii" },
  { n: "Anchorage", c: "United States", cc: "US", tz: "America/Anchorage", la: 61.22, lo: -149.9 },
  { n: "Toronto", c: "Canada", cc: "CA", tz: "America/Toronto", la: 43.65, lo: -79.38 },
  { n: "Montreal", c: "Canada", cc: "CA", tz: "America/Toronto", la: 45.5, lo: -73.57 },
  { n: "Vancouver", c: "Canada", cc: "CA", tz: "America/Vancouver", la: 49.28, lo: -123.12 },
  { n: "Mexico City", c: "Mexico", cc: "MX", tz: "America/Mexico_City", la: 19.43, lo: -99.13 },
  { n: "Bogotá", c: "Colombia", cc: "CO", tz: "America/Bogota", la: 4.71, lo: -74.07 },
  { n: "Lima", c: "Peru", cc: "PE", tz: "America/Lima", la: -12.05, lo: -77.04 },
  { n: "Santiago", c: "Chile", cc: "CL", tz: "America/Santiago", la: -33.45, lo: -70.67 },
  { n: "Buenos Aires", c: "Argentina", cc: "AR", tz: "America/Argentina/Buenos_Aires", la: -34.6, lo: -58.38 },
  { n: "São Paulo", c: "Brazil", cc: "BR", tz: "America/Sao_Paulo", la: -23.55, lo: -46.63, a: "sao paulo" },
  { n: "Rio de Janeiro", c: "Brazil", cc: "BR", tz: "America/Sao_Paulo", la: -22.91, lo: -43.17 },
  { n: "Panama City", c: "Panama", cc: "PA", tz: "America/Panama", la: 8.98, lo: -79.52 },
  { n: "San Juan", c: "Puerto Rico", cc: "PR", tz: "America/Puerto_Rico", la: 18.47, lo: -66.11 }
];
